name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#     - name: npm install
#       run: |
#         npm install
#     - name: npm test
#       run: |
#         npm test 
#       env:
#         CI: true
    - name: "Create .netrc for Heroku Auth"
      shell: bash
      run: |
        `cat >~/.netrc <<EOF
        machine api.heroku.com
            login $EMAIL
            password $HEROKU_AUTH_TOKEN
        machine git.heroku.com
            login $EMAIL
            password $HEROKU_AUTH_TOKEN
        EOF`
      env:
        EMAIL: ${{ secrets.EMAIL }}
        HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
    - name: "Add remote"
      shell: "bash"
      run: |
        heroku git:remote --a $HEROKU_APP_NAME
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }} 
