name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: "Checkout limistah:url-shortener"
      uses: actions/checkout@v1
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: "huong-dang/dearGenie"
        ref: "master"
#     - name: "Set up git config"
#       run: |
#         git config user.email "huong@huong.com" && git config user.name "USER NAME" && git commit --allow-empty -m "Trigger build"
#     - name: npm install
#       run: |
#         npm install
#     - name: npm test
#       run: |
#         npm test 
#       env:
#         CI: true
    - uses: akhileshns/heroku-deploy@master # This is the action we are importing
      with: # It accepts some arguments to work, we can pass the argument using `with`
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # This is the same as the auth key we generated earlier
        heroku_app_name: "dear-genie-dev" #Must be unique in Heroku
        heroku_email: ${{secrets.EMAIL}} # Email attached to the account
        justlogin: true
    - run: |
        git config user.name "huong" && git config user.email "huong@huong.com"
        git remote add heroku-dev https://git.heroku.com/dear-genie-dev.git
        git push heroku-dev master
