name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: "Checkout limistah:url-shortener"
      uses: actions/checkout@v1
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: "huong-dang/dearGenie"
        ref: "master"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#     - name: npm install
#       run: |
#         npm install
#     - name: npm test
#       run: |
#         npm test 
#       env:
#         CI: true
    - name: "Create .netrc for Heroku Auth"
      shell: bash
      run: |
        `cat >~/.netrc <<EOF
        machine api.heroku.com
            login $EMAIL
             password $HEROKU_AUTH_TOKEN
        machine git.heroku.com
            login $EMAIL
            password $HEROKU_AUTH_TOKEN
        EOF`
      env:
        EMAIL: ${{ secrets.EMAIL }}
        HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_API_KEY }}
    - name: "Add remote"
      shell: "bash"
      run: |
         heroku git:remote --app dear-genie-dev
    - name: "Push to heroku"
      shell: "bash"
      run: |
        git push heroku HEAD:master
