name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: "Checkout branch"
      uses: actions/checkout@v1
    - run: |
          ssh-keygen -t rsa -f /home/runner/.ssh/id_rsa -q -P ""
    - run: |
          heroku keys:add /home/runner/.ssh/id_rs
#     - name: npm install
#       run: |
#         npm install
#     - name: "Run unit tests"
#       run: |
#         npm test 
#       env:
#         CI: true
# Let's revisit this another time
    - uses: akhileshns/heroku-deploy@master # This is the action we are importing
      with: # It accepts some arguments to work, we can pass the argument using `with`
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # This is the same as the auth key we generated earlier
        heroku_app_name: "dear-genie-dev" #Must be unique in Heroku
        heroku_email: ${{secrets.EMAIL}} # Email attached to the account
        justlogin: true
    - run: |
        git config user.name "huong" && git config user.email "huong@huong.com"
        git remote add heroku-dev git@heroku.com:dear-genie-dev.git
        git push heroku-dev HEAD:master
