name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#     - name: npm install
#       run: |
#         npm install
#     - name: npm test
#       run: |
#         npm test 
#       env:
#         CI: true
    - name: Install heroku
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
    - name: Heroku login
      run: |
        machine api.heroku.com
        login ${{ secrets.EMAIL }}
        password ${{ secrets.HEROKU_API_KEY }}
        machine git.heroku.com
        login ${{ secrets.EMAIL }}
        password ${{ secrets.HEROKU_API_KEY }}
